[package]
name = "garanddev/rcord"
description = "Read more at https://github.com/GarandDev/rcord"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["sourcemap.json", "TODO", "aftman.toml", "ts", "examples"]

[dependencies]
