name: Publish to Wally and Update Roblox Module Script

on:
  workflow_dispatch:  # Allows manual triggering from GitHub
  push:
    branches:
      - main  # Run this workflow on push to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish to Wally
      run: |
        wally publish
      env:
        WALLY_API_KEY: ${{ secrets.WALLY_API_KEY }}}

    - name: Update Roblox Module Script
      run: |
        curl -X POST "https://apis.roblox.com/assets/v1/assets/${{ secrets.ASSET_ID }}" \
        -H "x-api-key: ${{ secrets.ROBLOX_API_KEY }}" \
        -F "file=@./path/to/your/ModuleScript.lua" \
        -F "type=Script"
      env:
        ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        ASSET_ID: ${{ secrets.ASSET_ID }}
