name: Publish to Wally and Update Roblox Module Script

on:
  workflow_dispatch:  # Allows manual triggering from GitHub
  push:
    branches:
      - main  # Run this workflow on push to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Update version in wally.toml
      run: |
        VERSION=$(cat VERSION)
        echo "Updating wally.toml to version $VERSION"
        sed -i "s/^version = \".*\"/version = \"$VERSION\"/" wally.toml

    - name: Aftman install
      uses: ok-nick/setup-aftman@v0.4.2

    - name: Wally login
      run: wally login --token ${{ secrets.WALLY_API_KEY }}

    - name: Publish rCord
      run: wally publish

    - name: Wally logout
      run: wally logout

    - name: Update Roblox Module Script
      run: |
        curl --location --request PATCH 'https://apis.roblox.com/assets/v1/assets/${{ secrets.ASSET_ID }}' \
          --header 'x-api-key: ${{ secrets.ROBLOX_API_KEY }}' \
          --form 'request={
            "assetId": "${{ secrets.ASSET_ID }}",
            "name": "rCord"
          }' \
          --form 'fileContent=@src/init.lua;type=application/x-lua;filename=rCord.lua'
      env:
        ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        ASSET_ID: ${{ secrets.ASSET_ID }}
